version: '3'
services: 
    web: 
        build: .
        ports: 
            - "4000:3000"
        depends_on:
            - mongo
        volumes:
            - .:/usr/src/app    
    mongo:
        image: mongo
        ports: 
            - "27018:27017"
        volumes:
            - mongodb_data:/data/db
volumes:
    mongodb_data:
        driver: local
